spring:
  datasource:
    url: ${URL_DB:jdbc:postgresql://localhost:5432/postgres}
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        hbm2ddl:
          auto: create
        format_sql: true
        show_sql: true
  application:
    name: history

eureka:
  client:
    service-url:
      defaultZone: ${DISCOVERY_URL:http://localhost:8761/eureka}


server.port: ${SERVER_PORT:8083}
