spring:
  datasource:
    url: ${URL_DB:jdbc:postgresql://localhost:5432/postgres}
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        hbm2ddl:
          auto: validate
        format_sql: true
        show_sql: true